In [4]:
import numpy as np 
a = np.array([[1,2,3], [4,5,6]],dtype=np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [5]:
print(a.shape)

(2, 3)


In [6]:
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [10]:
#Array Ex

a = np.array([[[8,9], [10,11], [12,13]]])
print(a)

[[[ 8  9]
  [10 11]
  [12 13]]]


In [9]:
a = np.array([[[8,9], [10,11], [12,13]]], ndmin=6)
print(a)

[[[[[[ 8  9]
     [10 11]
     [12 13]]]]]]


In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
# Abbey taught us how to use f' strings 

def a_function(x,y):
   print(f' x + y = {(x+y)}')

a_function(4,2)   

 x + y = 6


# Group Excercise Wk3

In [61]:
def a_function(a,b):
   print(f' a + b = {(a+b)}')
   print(f' a - b = {(a-b)}') 
   if (a-b==0):
        print(' a - b = zero')
   print(f' a * b = {(a*b)}')
        
   
a_function(3,5)   

 a + b = 8
 a - b = -2
 a * b = 15


In [62]:
a_function(3,3) 

 a + b = 6
 a - b = 0
 a - b = zero
 a * b = 9


In [86]:
def a_function(a,b):
   print(f' a + b = {(a+b)}')

   if (a-b==0):
        print(' a - b = zero')
        
   elif (a-b!=0):
        print(f' a - b = {(a-b)}')      
        
   print(f' a * b = {(a*b)}')
        

a_function(3,3)   

 a + b = 6
 a - b = zero
 a * b = 9


In [89]:
#rechecking a-b functionality 

def a_function(a,b):
   print(f' a + b = {(a+b)}')

   if (a-b==0):
        print(' a - b = zero')
        
   elif (a-b!=0):
        print(f' a - b = {(a-b)}')      
        
   print(f' a * b = {(a*b)}')
        

a_function(3,9)   

 a + b = 12
 a - b = -6
 a * b = 27
